config/routes.rb
Rails.application.routes.draw do
  root to: "main#index"

  post '/guess/:letter', to: 'main#guess', as: :guess
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @game = Game.new
  end

  def guess
    @game = Game.new
    @guessed_letters = @game.guessed_letters
    letter = params[:letter].upcase

    @guessed_letters << letter

    if !@game.word.include?(letter)
      @game.max_attempts -= 1
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hangman</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/_letter_bank.html.erb
<div class="letter-bank">
  <% ('A'..'Z').each do |letter| %>
    <%= button_to letter, guess_path(letter: letter), method: :post, remote: true, class: "btn btn-secondary" %>
  <% end %>
</div>

app/views/main/index.html.erb
<div class="game-image">
  <% if @guessed_letters.nil? %>
    <img src="<%= asset_path('new_game.jpeg') %>" alt="empty hangman game image" class="game-image">
  <% end %>
</div>

<div class="guessed-letters">
  <%= @guessed_letters %>
</div>

<div class="letter-bank">
  <% ('A'..'Z').each do |letter| %>
    <%= button_to letter, guess_path(letter: letter), method: :post, remote: true, class: "btn btn-light btn-outline-dark btn-sm" %>
  <% end %>
</div>